### ISSUE TITLE
Permission in marshmallow

### ISSUE THREAD

**Issue by ashudb70** [kaliturin/BlackList#1]
your app indeed is great have pulled for my college project request 
i guess there is bug of permission with marshmallow api 23 every time i open app it asks for permission again

**Comment by kaliturin** [comment]
Thank you very much for you notice. It was very helpful. I fixed it.
I hope you join to beta testers team.
https://play.google.com/apps/testing/com.kaliturin.blacklist

**Comment by ashudb70** [comment]
thanks for such build have joined your beta tester program and can help in contributing to add additional features like sorting spam messages from Advertisers. indeed its great build. commented on your play store build too 🥇
