### ISSUE TITLE
Update page since app is on F-Droid

### ISSUE THREAD

**Issue by esmoak** [kaliturin/BlackList#11]
This page could benefit from having a link button to F-Droid near the Play Store button:

https://github.com/kaliturin/BlackList

Thank you so much for getting this in fdroid. And the app is amazing. 

Do you have a donate option anywhere?  I couldn't find a donate link.

**Comment by kaliturin** [comment]
Thanks! 
I accepted the pull request with a link button to F-Droid. I don't accept donation for this project nor sure I will support is as it is. But I consider to rewrite it in Kotlin with new features someday.
