### ISSUE TITLE
dual sim issue

### ISSUE THREAD

**Issue by ashudb70** [kaliturin/BlackList#2]
what if the sim is dual sim how can i differentiate from which sim to add for blacklist

**Comment by kaliturin** [comment]
At the moment app does not read anything from SIM card directly. All contacts are read from phone's contacts list. So I guess you should at first move contacts from SIM to phone in contacts default app: Contacts -> Menu -> Import/Export -> From SIM to Phone.

**Comment by ashudb70** [comment]
thank you bro can u help if i wish to add navigation drawer to different activity how can i?

**Comment by kaliturin** [comment]
I can only tell you what I did when I was studying like you now. It was the easiest way: in Android Studio create a new project with predefined template: Navigation Drawer Activity. Then research how it is done and add your own functionality. It is pretty simple stuff. Only practice with it helps you.
