### ISSUE TITLE
Consider submitting to f-droid?

### ISSUE THREAD

**Issue by craftyguy** [kaliturin/BlackList#6]
Great project! Have you considered submitting it to f-droid? If not, would you be OK with me submitting it on your behalf?

**Comment by kaliturin** [comment]
Thank you! Sure! I would appreciate if you do it.

**Comment by craftyguy** [comment]
Ok, thanks, I will! They recommend you tag releases, would you might tagging a release in this repo?

**Comment by kaliturin** [comment]
Have done!
https://github.com/kaliturin/BlackList/releases/tag/v1.2.12

**Comment by craftyguy** [comment]
Awesome!

FYI, here's the request I filed: https://gitlab.com/fdroid/rfp/issues/540

I copied your description, etc. Feel free to propose changes if you'd like!

**Comment by kaliturin** [comment]
Thank you for your contribution!

**Comment by esmoak** [comment]
@craftyguy You are a saint for helping to make this happen. I love this app so much and am thankful to have a full feautured call blocker in F-Droid.

**Comment by esmoak** [comment]
@craftyguy You are a saint for helping to make this happen. I love this app so much and am thankful to have a full feautured call blocker in F-Droid.
