### ISSUE TITLE
Feature request - Redirect unknown numbers to voicemail

### ISSUE THREAD

**Issue by Thrilleratplay** [kaliturin/BlackList#7]
Lately, at least for me, telemarketers have not been reusing numbers so blacklisting individual numbers  does not help. Yet, when I dismiss the call, they tend not to leave a voicemail.  It would be nice if this could be automated.

Could incoming calls numbers that are not whitelisted or listed in Contacts be redirected to voicemail.  An option to disable ringing/vibration notifications when this occurs would also be helpful to prevent these types of distractions.

**Comment by kaliturin** [comment]
Redirection to a voicemail is not implemented. This is a simple blocker, was made just for fun. But I will consider to add this feature into a wishlist. Someday.
